name: Urchin.ui
version: 1.0.0
description: User interface for configuring the rules in Urchin server
author: Martin Halliday
homepage: https://github.com/Bikeman868/Urchin
documentation: https://github.com/Bikeman868/Urchin/tree/master/Urchin.Server.Owin

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: any
  dart_to_js_script_rewriter: any

transformers:
- $dart2js
  