name: Urchin.ui
version: 1.0.0
description: User interface for configuring the rules in Urchin server
author: Martin Halliday
homepage: https://github.com/Bikeman868/Urchin
documentation: https://github.com/Bikeman868/Urchin/tree/master/Urchin.Server.Owin
